before_script:
  - docker info
  - '[ -d tmp ] || mkdir tmp'
  - MAJOR_VERSION=$(echo "${CI_COMMIT_TAG#v}" | cut -d'.' -f1)
  - MINOR_VERSION=$(echo "${CI_COMMIT_TAG#v}" | cut -d'.' -f2)
  - '[ "x$CI_COMMIT_TAG" != "x" ] && RELEASE="${MAJOR_VERSION}.${MINOR_VERSION}" || RELEASE=master'
  - git clone --single-branch --branch $RELEASE https://github.com/OSC/ondemand-packaging.git tmp/ondemand-packaging
  - cp /systems/osc_certs/gpg/ondemand/.gpgpass $CI_PROJECT_DIR/tmp/ondemand-packaging/
  - cp /systems/osc_certs/gpg/ondemand/ondemand.sec $CI_PROJECT_DIR/tmp/ondemand-packaging/
stages:
  - build
  - deploy

variables:
  GIT_STRATEGY: clone

rpm-build-nightly-el7:
  stage: build
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
  script:
    - export SHA=$(git rev-parse --short HEAD)
    - export LAST_TAG=$(git describe --tags --abbrev=0)
    - export MAJOR_MINOR=${LAST_TAG%.*}
    - bundle install --path vendor/bundle --without test
    - export VERSION="${MAJOR_MINOR#v}.$(date +%Y%m%d)-1.${SHA}.nightly"
    - bundle exec rake package:tar
    - ./tmp/ondemand-packaging/build.sh -w $CI_PROJECT_DIR/tmp/work -o $CI_PROJECT_DIR/tmp/output -V v${VERSION} -u -v -C -d el7 $CI_PROJECT_DIR/packaging
  artifacts:
    paths:
      - tmp/output
    name: "$CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA"

rpm-build-nightly-el8:
  stage: build
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
  script:
    - export SHA=$(git rev-parse --short HEAD)
    - export LAST_TAG=$(git describe --tags --abbrev=0)
    - export MAJOR_MINOR=${LAST_TAG%.*}
    - bundle install --path vendor/bundle --without test
    - export VERSION="${MAJOR_MINOR#v}.$(date +%Y%m%d)-1.${SHA}.nightly"
    - bundle exec rake package:tar
    - ./tmp/ondemand-packaging/build.sh -w $CI_PROJECT_DIR/tmp/work -o $CI_PROJECT_DIR/tmp/output -V v${VERSION} -u -v -C -d el8 $CI_PROJECT_DIR/packaging
  artifacts:
    paths:
      - tmp/output
    name: "$CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA"

rpm-build-el7:
  stage: build
  only:
    - tags
  script:
    - ./tmp/ondemand-packaging/build.sh -w $CI_PROJECT_DIR/tmp/work -o $CI_PROJECT_DIR/tmp/output -V $CI_COMMIT_TAG -u -v -C -d el7 $CI_PROJECT_DIR/packaging
  artifacts:
    paths:
      - tmp/output
    name: "$CI_PROJECT_NAME-$CI_COMMIT_TAG"

rpm-build-el8:
  stage: build
  only:
    - tags
  script:
    - ./tmp/ondemand-packaging/build.sh -w $CI_PROJECT_DIR/tmp/work -o $CI_PROJECT_DIR/tmp/output -V $CI_COMMIT_TAG -u -v -C -d el8 $CI_PROJECT_DIR/packaging
  artifacts:
    paths:
      - tmp/output
    name: "$CI_PROJECT_NAME-$CI_COMMIT_TAG"

rpm-deploy-nightly:
  stage: deploy
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
  script:
    - ./tmp/ondemand-packaging/release.py --debug --pkey /systems/osc_certs/ssh/ondemand-packaging/id_rsa -c nightly ./tmp/output/*

rpm-deploy-build:
  stage: deploy
  only:
    - tags
  script:
    - ./tmp/ondemand-packaging/release.py --debug --pkey /systems/osc_certs/ssh/ondemand-packaging/id_rsa -c build -r $CI_COMMIT_TAG ./tmp/output/*

rpm-deploy-ci:
  stage: deploy
  only:
    - tags
  script:
    - ./tmp/ondemand-packaging/release.py --debug --pkey /systems/osc_certs/ssh/ondemand-packaging/id_rsa -c ci ./tmp/output/*

rpm-deploy:
  stage: deploy
  only:
    - tags
  except:
    variables:
      - $CI_COMMIT_TAG =~ /.*_.*/
  script:
    - ./tmp/ondemand-packaging/release.py --debug --pkey /systems/osc_certs/ssh/ondemand-packaging/id_rsa -c main ./tmp/output/*
